var lambda = require('./lib/lambda.js')
var apigateway = require('./lib/apigateway.js')
var deploy = require('./lib/deploy.js')
var dataProcess = require('./lib/dataProcess.js')
var packagers = require('./lib/packagers.js')
var SETTINGS = require('./lib/settings.js').constants

apigateway.purgeApi()
  .then(packagers.buildUnifiedLambdaPackage)
  .then(dataProcess.buildUnifiedLambdaFunction)
  .then(lambda.deployLambdaFunction)
  .then(dataProcess.buildLambdaURI)
  .then(dataProcess.buildRootResources)
  .then(deploy.deployResources)
  .then((data) => console.log(data))
  .catch((err) => console.log(err.stack))
